### ISSUE TITLE
It does not compile on esp8266 v3.1.2

### ISSUE THREAD

**Issue by IlyaB-git** [distrakt/OmEspHelpers#13]
I'm trying an example LedController, use board NodeMCU 1.0

**Comment by distrakt** [comment]
Thankyou Ilya! I just updated to 3.1.2 and I see many errors all similar to:

/Users/poly/Documents/Arduino/libraries/OmEspHelpers/src/OmOta.cpp:228:67: error: conversion from 'IPAddress' to 'long unsigned int' is ambiguous

Will repair...

Is this the same error you see?

...

I will roll out a new release in future; in the mean time, the fix is to edit OmUtil.h and OmUtil.cpp

```
// in OmUtil.h:
const char *omIpToString(unsigned int, bool flip = false);

// in OmUtil.cpp:
const char *omIpToString(unsigned int ip, bool flip)

```
In both cases changing from "_unsigned long_" to "_unsigned int_".
On mac the files are installed at:
/Users/USERNAME/Documents/Arduino/libraries/OmEspHelpers/src/

**Comment by IlyaB-git** [comment]
Yes, I have similar errors. What is the working version of the esp8266 board? Thanks!

**Comment by distrakt** [comment]
You can go back to ESP 8266 board version 2.7.x and it will work.
(Or incorporate the diffs above to OmUtil.cpp/h)

**Comment by distrakt** [comment]
This is now fixed in latest releast 1.9! 
If you can confirm it works for you? thankyou.
